FROM debian:stretch-20190204

ENV OS debian
ENV STAGE dev

ENV OPENVAS_SRC /root/openvas-src
RUN mkdir -p ${OPENVAS_SRC}
WORKDIR ${OPENVAS_SRC}

# gvm-libs
ENV APP gvm-libs
RUN mkdir -p ${OPENVAS_SRC}/${APP}
WORKDIR ${OPENVAS_SRC}/${APP}
COPY ./src/${APP}/deps/${OS}-deps.sh .
RUN chmod +x ./${OS}-deps.sh && ./${OS}-deps.sh
COPY ./src/${APP}/build.sh .
RUN chmod +x ./build.sh && ./build.sh ${STAGE}

# gvmd
ENV APP gvmd
RUN mkdir -p ${OPENVAS_SRC}/${APP}
WORKDIR ${OPENVAS_SRC}/${APP}
COPY ./src/${APP}/deps/${OS}-deps.sh .
RUN chmod +x ./${OS}-deps.sh && ./${OS}-deps.sh
COPY ./src/${APP}/build.sh .
RUN chmod +x ./build.sh && ./build.sh ${STAGE}

# openvas-smb
ENV APP openvas-smb
RUN mkdir -p ${OPENVAS_SRC}/${APP}
WORKDIR ${OPENVAS_SRC}/${APP}
COPY ./src/${APP}/deps/${OS}-deps.sh .
RUN chmod +x ./${OS}-deps.sh && ./${OS}-deps.sh
COPY ./src/${APP}/build.sh .
RUN chmod +x ./build.sh && ./build.sh ${STAGE}

# openvas-scanner
ENV APP openvas-scanner
RUN mkdir -p ${OPENVAS_SRC}/${APP}
WORKDIR ${OPENVAS_SRC}/${APP}
COPY ./src/${APP}/deps/${OS}-deps.sh .
RUN chmod +x ./${OS}-deps.sh && ./${OS}-deps.sh
COPY ./src/${APP}/build.sh .
RUN chmod +x ./build.sh && ./build.sh
COPY ./src/${APP}/config/openvassd.conf /usr/local/etc/openvas/openvassd.conf
COPY ./src/${APP}/config/redis.conf /etc/redis.conf

WORKDIR /
RUN rm -rf ${OPENVAS_SRC}

ENV APP sshvpn
COPY ./scripts/bin/${APP}/greenbone-setup.sh /usr/local/bin
RUN chmod +x /usr/local/bin/greenbone-setup.sh

COPY ./scripts/entrypoint/${APP}/docker-entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

VOLUME ["/usr/local/var/lib/openvas"]
EXPOSE 9390 9391
