---

- name: "Deploy 'Greenbone GVM'"
  hosts: localhost
  gather_facts: no
  vars:
    versions_file: "../dockerfile/VERSIONS"
  tasks:

    - name: "Run GVM docker-compose"
      docker_compose:
        project_name: gvm
        project_src: ../docker-compose/stable
        files: docker-compose.yml
        env_file: "{{ versions_file }}"
      register: output

    - debug:
        var: output
