ARG gvmd_version
ARG postgres_gvm_version

FROM dgiorgio/gvmd:${gvmd_version} AS gvmd
FROM postgres:${postgres_gvm_version}

RUN apt update -y && apt install -y --no-install-recommends --fix-missing \
  git cmake gcc make clang-format pkg-config libglib2.0-dev libgpgme11-dev \
  libgnutls28-dev uuid-dev libssh-gcrypt-dev libldap2-dev libhiredis-dev \
  libfreeradius-dev doxygen xmltoman libxml2-dev libical-dev gnutls-bin \
  xsltproc sqlfairy libsqlite3-dev libpq-dev texlive-latex-base xmlstarlet \
  zip rpm dpkg fakeroot nsis gnupg wget sshpass ssh-client socat snmp smbclient \
  python3 python3-lxml haveged cron postgresql-11 postgresql-server-dev-11 \
  libradcli-dev libgcrypt20-dev libpaho-mqtt-dev \
  && rm -rf /var/lib/apt/lists/*

COPY --from=gvmd /usr/local/lib/libgvm* /usr/local/lib/

WORKDIR /usr/local/lib
RUN chmod -R 644 /usr/local/lib/libgvm* \
  && ldconfig
EXPOSE 5432
