FROM dgiorgio/gvmlibs:21.4.2

RUN apt update -y && apt install -y --no-install-recommends --fix-missing \
  wget gnupg2 \
  && echo 'deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
  && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends --fix-missing \
  git cmake gcc make clang-format pkg-config libglib2.0-dev libgnutls28-dev \
  libical-dev xml-twig-tools gnutls-bin doxygen xmltoman xsltproc sqlfairy \
  libsqlite3-dev texlive-latex-base texlive-latex-extra xmlstarlet zip rpm dpkg \
  fakeroot nsis gnupg wget sshpass ssh-client socat snmp smbclient python3 python3-lxml \
  haveged cron libpq-dev postgresql-client-11 postgresql-server-dev-11 rsync \
  python3-pip dma \
  && apt install -y texlive-fonts-recommended \
  && rm -rf /var/lib/apt/lists/*

ARG STAGE
ENV STAGE ${STAGE}

# gvmd
RUN mkdir -p /root/gvm-src/gvmd
WORKDIR /root/gvm-src/gvmd
COPY ./src/gvmd/commit/${STAGE} ./src/gvmd/build.sh ./
RUN chmod +x ./build.sh && ./build.sh ${STAGE} \
  && apt remove -y git cmake gcc make clang-format pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN rm -rf /root/gvm-src

# install https://github.com/kolypto/j2cli
RUN pip3 install j2cli setuptools
# config smtp
COPY ./src/gvmd/config/dma.conf.j2 ./src/gvmd/config/auth.conf.j2 /etc/dma/

COPY ./entrypoint/gvmd/docker-entrypoint.sh ./src/gvmd/scripts/* /usr/local/bin/
RUN chmod 755 /usr/local/bin/* \
  && chown -R gvm. /usr/local/var

COPY --from=dgiorgio/openvas-scanner:21.4.2-1 /usr/local/bin/greenbone-nvt-sync /usr/local/bin/

USER gvm
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["/usr/local/sbin/gvmd", "-f", "-v", "--osp-vt-update=/var/run/ospd/ospd.sock", "--listen=0.0.0.0", "--port=9390"]

VOLUME ["/usr/local/var/lib/gvm"]
EXPOSE 9390
