FROM debian:stretch-20190708

RUN apt update -y && apt install -y --no-install-recommends --fix-missing \
  git cmake gcc make clang-format pkg-config libglib2.0-dev libgnutls28-dev \
  uuid-dev libssh-gcrypt-dev libgpgme11-dev libhiredis-dev libldap2-dev \
  doxygen xmltoman libfreeradius-dev \
  && rm -rf /var/lib/apt/lists/*

ARG STAGE
ENV STAGE ${STAGE}

# gvm-libs
RUN mkdir -p /root/gvm-src/gvm-libs
WORKDIR /root/gvm-src/gvm-libs
COPY ./src/gvm-libs/build.sh ./src/gvm-libs/commit/${STAGE} ./
RUN chmod +x ./build.sh && ./build.sh ${STAGE} \
  && apt remove -y git cmake gcc make clang-format pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN rm -rf /root/gvm-src
