FROM debian:stretch-20191118

RUN apt update -y && apt install -y --no-install-recommends --fix-missing \
  git cmake gcc make clang-format pkg-config libglib2.0-dev libgpgme11-dev \
  libgnutls28-dev uuid-dev libssh-gcrypt-dev libldap2-dev libhiredis-dev \
  libfreeradius-dev doxygen xmltoman libxml2-dev sudo \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir -p /etc/sudoers.d \
  && useradd -s /bin/bash -m gvm \
  && echo 'gvm ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/gvm

ARG STAGE
ENV STAGE ${STAGE}

# gvm-libs
RUN mkdir -p /root/gvm-src/gvm-libs
WORKDIR /root/gvm-src/gvm-libs
COPY ./src/gvm-libs/build.sh ./src/gvm-libs/commit/${STAGE} ./
RUN chmod +x ./build.sh && ./build.sh ${STAGE} \
  && apt remove -y git cmake gcc make clang-format pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN rm -rf /root/gvm-src
