ARG gvmlibs_version
FROM dgiorgio/gvmlibs:${gvmlibs_version}

# yarn nodejs
RUN apt update -y && apt install -y curl apt-transport-https \
  && curl --silent --show-error https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
  && apt update -y && apt install -y --no-install-recommends --fix-missing \
  git cmake gcc g++ make clang-format pkg-config curl libglib2.0-dev \
  libgnutls28-dev libmicrohttpd-dev gettext python-polib libxml2-dev \
  doxygen xmltoman ssh texlive-latex-extra texlive-fonts-recommended \
  && apt install -y --no-install-recommends nodejs yarn \
  && rm -rf /var/lib/apt/lists/*


ARG STAGE
ENV STAGE ${STAGE}
ARG gsad_version
ENV gsad_version ${gsad_version}
ARG gsa_version
ENV gsa_version ${gsa_version}

# gsad
RUN mkdir -p /root/gvm-src/gsad
WORKDIR /root/gvm-src/gsad
COPY ./src/gsad/commit/${STAGE} ./src/gsad/build.sh ./
RUN chmod +x ./build.sh && ./build.sh ${STAGE}

# gsa
RUN mkdir -p /root/gvm-src/gsa
WORKDIR /root/gvm-src/gsa
COPY ./src/gsa/commit/${STAGE} ./src/gsa/build.sh ./
RUN chmod +x ./build.sh && ./build.sh ${STAGE} \
  && apt remove -y git cmake gcc g++ make pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN rm -rf /root/gvm-src

COPY ./entrypoint/gsa/docker-entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

USER gvm
WORKDIR /home/gvm
ENTRYPOINT ["/tini", "--", "/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 80 443
